CREATE TABLE execution_opportunity (
    id BIGINT NOT NULL AUTO_INCREMENT,
    symbol VARCHAR(30) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    status VARCHAR(30) NOT NULL,
    started_at TIMESTAMP(6) NOT NULL,
    last_evidence_at TIMESTAMP(6) NOT NULL,
    latest_signal_id BIGINT NULL,
    evidence_count INT NOT NULL DEFAULT 0,
    buy_count INT NOT NULL DEFAULT 0,
    watch_count INT NOT NULL DEFAULT 0,
    neutral_count INT NOT NULL DEFAULT 0,
    evidence_score INT NOT NULL DEFAULT 0,
    average_signal_score INT NOT NULL DEFAULT 0,
    average_confidence INT NOT NULL DEFAULT 0,
    five_minute_decision VARCHAR(30) NULL,
    one_hour_decision VARCHAR(30) NULL,
    execution_source VARCHAR(40) NULL,
    recommended_position_percent INT NOT NULL DEFAULT 0,
    decision_code VARCHAR(80) NULL,
    decision_explanation VARCHAR(2000) NULL,
    executed_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_execution_opportunity_latest_signal
        FOREIGN KEY (latest_signal_id) REFERENCES trade_signal(id),
    INDEX idx_execution_opportunity_symbol_status (symbol, status, last_evidence_at),
    INDEX idx_execution_opportunity_latest_signal (latest_signal_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
