CREATE TABLE analysis_test_run (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    test_name VARCHAR(150) NOT NULL,
    symbol VARCHAR(30) NOT NULL,
    start_time TIMESTAMP(6) NOT NULL,
    end_time TIMESTAMP(6) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    progress_percent INT NOT NULL DEFAULT 0,
    current_step VARCHAR(255) NULL,
    source_signal_count INT NOT NULL DEFAULT 0,
    replay_signal_count INT NOT NULL DEFAULT 0,
    neutralized_original_bearish_count INT NOT NULL DEFAULT 0,
    corrected_hard_reversal_count INT NOT NULL DEFAULT 0,
    historical_hard_reversal_count INT NOT NULL DEFAULT 0,
    error_message VARCHAR(2000) NULL,
    started_at TIMESTAMP(6) NULL,
    completed_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    INDEX idx_analysis_test_run_created (created_at),
    INDEX idx_analysis_test_run_symbol_time (symbol, start_time, end_time)
);

CREATE TABLE analysis_test_signal (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    test_run_id BIGINT NOT NULL,
    source_signal_id BIGINT NULL,
    symbol VARCHAR(30) NOT NULL,
    interval_code VARCHAR(10) NOT NULL,
    candle_open_time TIMESTAMP(6) NULL,
    generated_at TIMESTAMP(6) NOT NULL,
    latest_price DECIMAL(30,12) NULL,
    original_decision VARCHAR(30) NULL,
    final_decision VARCHAR(30) NULL,
    execution_effective_decision VARCHAR(30) NULL,
    total_score INT NULL,
    confidence_score INT NULL,
    trend_score INT NULL,
    volume_score INT NULL,
    momentum_score INT NULL,
    decision_authority_corrected TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_analysis_test_signal_run FOREIGN KEY (test_run_id) REFERENCES analysis_test_run(id) ON DELETE CASCADE,
    INDEX idx_analysis_test_signal_run_time (test_run_id, generated_at),
    INDEX idx_analysis_test_signal_run_interval (test_run_id, interval_code)
);

CREATE TABLE execution_opportunity_test (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    test_run_id BIGINT NOT NULL,
    source_signal_id BIGINT NULL,
    symbol VARCHAR(30) NOT NULL,
    generated_at TIMESTAMP(6) NOT NULL,
    current_final_decision VARCHAR(30) NULL,
    current_original_decision VARCHAR(30) NULL,
    five_minute_decision VARCHAR(30) NULL,
    one_hour_decision VARCHAR(30) NULL,
    old_hard_bearish_reversal TINYINT(1) NOT NULL DEFAULT 0,
    corrected_hard_bearish_reversal TINYINT(1) NOT NULL DEFAULT 0,
    decision_code VARCHAR(80) NULL,
    decision_explanation VARCHAR(2000) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_execution_opportunity_test_run FOREIGN KEY (test_run_id) REFERENCES analysis_test_run(id) ON DELETE CASCADE,
    INDEX idx_execution_opportunity_test_run_time (test_run_id, generated_at)
);

CREATE TABLE analysis_test_result (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    test_run_id BIGINT NOT NULL,
    candles_1m INT NOT NULL DEFAULT 0,
    signals_1m_historical INT NOT NULL DEFAULT 0,
    replayable_1m_events INT NOT NULL DEFAULT 0,
    candles_5m INT NOT NULL DEFAULT 0,
    signals_5m_historical INT NOT NULL DEFAULT 0,
    replayable_5m_events INT NOT NULL DEFAULT 0,
    candles_1h INT NOT NULL DEFAULT 0,
    signals_1h_historical INT NOT NULL DEFAULT 0,
    replayable_1h_events INT NOT NULL DEFAULT 0,
    decision_authority_corrections INT NOT NULL DEFAULT 0,
    old_hard_bearish_reversals INT NOT NULL DEFAULT 0,
    corrected_hard_bearish_reversals INT NOT NULL DEFAULT 0,
    cadence_path_passed TINYINT(1) NOT NULL DEFAULT 0,
    decision_authority_passed TINYINT(1) NOT NULL DEFAULT 0,
    test_passed TINYINT(1) NOT NULL DEFAULT 0,
    notes VARCHAR(2000) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_analysis_test_result_run FOREIGN KEY (test_run_id) REFERENCES analysis_test_run(id) ON DELETE CASCADE,
    UNIQUE KEY uk_analysis_test_result_run (test_run_id)
);
