-- FIX-11Q: replay-only one-candle continuation grace counterfactual.
CREATE TABLE one_candle_continuation_grace_test (
    id BIGINT NOT NULL AUTO_INCREMENT,
    test_run_id BIGINT NOT NULL,
    position_test_id BIGINT NOT NULL,
    symbol VARCHAR(30) NOT NULL,
    grace_at TIMESTAMP(6) NOT NULL,
    grace_1m_signal_id BIGINT NULL,
    grace_candle_time TIMESTAMP(6) NOT NULL,
    price_at_grace DECIMAL(30,12) NOT NULL,
    entry_price DECIMAL(30,12) NOT NULL,
    take_profit_before_grace DECIMAL(30,12) NULL,
    take_profit_after_grace DECIMAL(30,12) NULL,
    current_1m_decision VARCHAR(30) NULL,
    five_minute_decision VARCHAR(30) NULL,
    one_hour_decision VARCHAR(30) NULL,
    trend_score INT NULL,
    trend_floor INT NULL,
    momentum_score INT NULL,
    momentum_floor INT NULL,
    baseline_action VARCHAR(60) NOT NULL,
    baseline_exit_price DECIMAL(30,12) NULL,
    baseline_pnl_usdt DECIMAL(30,12) NULL,
    baseline_pnl_percent DECIMAL(18,8) NULL,
    baseline_explanation TEXT NULL,
    next_1m_decision VARCHAR(30) NULL,
    next_5m_decision VARCHAR(30) NULL,
    next_1h_decision VARCHAR(30) NULL,
    variant_exit_time TIMESTAMP(6) NULL,
    variant_exit_price DECIMAL(30,12) NULL,
    variant_exit_reason VARCHAR(80) NULL,
    variant_pnl_usdt DECIMAL(30,12) NULL,
    variant_pnl_percent DECIMAL(18,8) NULL,
    pnl_delta_usdt DECIMAL(30,12) NULL,
    mfe_after_grace_percent DECIMAL(18,8) NULL,
    mae_after_grace_percent DECIMAL(18,8) NULL,
    grace_result VARCHAR(60) NULL,
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_fix11q_run_position (test_run_id, position_test_id),
    KEY idx_fix11q_run_grace (test_run_id, grace_at),
    KEY idx_fix11q_symbol_grace (symbol, grace_at)
);

CREATE TABLE one_candle_continuation_grace_test_archive LIKE one_candle_continuation_grace_test;
ALTER TABLE one_candle_continuation_grace_test_archive
    DROP PRIMARY KEY,
    DROP INDEX uk_fix11q_run_position,
    MODIFY id BIGINT NOT NULL,
    ADD COLUMN archive_batch_id BIGINT NOT NULL FIRST,
    ADD PRIMARY KEY (archive_batch_id, id),
    ADD KEY idx_fix11q_archive_run_grace (test_run_id, grace_at);
